server:
  port: 9090
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: picture-system-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    redisson:
      file: classpath:redisson.yaml
    # Lettuce连接池配置（Spring Boot 2.x 默认）
    lettuce:
      pool:
        # 最大活跃连接数
        max-active: 8
        # 最大空闲连接数
        max-idle: 8
        # 最小空闲连接数
        min-idle: 2
        # 连接池最大阻塞等待时间
        max-wait: 1000

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 50MB # 单个文件最大大小
      max-request-size: 50MB # 整个请求最大总大小

  # session 配置
  session:
    store-type: redis
    #  session 过期时间30天
    timeout: 2592000

knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: 接口文档描述
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.my.picturesystembackend.controller

# Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 如果 XML文件位置自定义了方法，需要指定
  configuration:
    map-underscore-to-camel-case: false # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 显示SQL语句
  global-config:
    db-config:
      id-type: assign_id # 主键策略
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
